// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import BarcodeLookupController from "./barcode_lookup_controller"
application.register("barcode-lookup", BarcodeLookupController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import CommandController from "./command_controller"
application.register("command", CommandController)

import ContextMenuController from "./context_menu_controller"
application.register("context-menu", ContextMenuController)

import DataTableController from "./data_table_controller"
application.register("data-table", DataTableController)

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import DebouncedSearchController from "./debounced_search_controller"
application.register("debounced-search", DebouncedSearchController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DropdownMenuController from "./dropdown_menu_controller"
application.register("dropdown-menu", DropdownMenuController)

import FieldVisibilityController from "./field_visibility_controller"
application.register("field-visibility", FieldVisibilityController)

import FormController from "./form_controller"
application.register("form", FormController)

import GeocodeLookupController from "./geocode_lookup_controller"
application.register("geocode-lookup", GeocodeLookupController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HoverCardController from "./hover_card_controller"
application.register("hover-card", HoverCardController)

import IconSearchController from "./icon_search_controller"
application.register("icon-search", IconSearchController)

import InputOtpController from "./input_otp_controller"
application.register("input-otp", InputOtpController)

import LoyaltyBrandController from "./loyalty_brand_controller"
application.register("loyalty-brand", LoyaltyBrandController)

import MenubarController from "./menubar_controller"
application.register("menubar", MenubarController)

import MessageScrollerController from "./message_scroller_controller"
application.register("message-scroller", MessageScrollerController)

import NavigationMenuController from "./navigation_menu_controller"
application.register("navigation-menu", NavigationMenuController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ResizableController from "./resizable_controller"
application.register("resizable", ResizableController)

import SearchPaletteController from "./search_palette_controller"
application.register("search-palette", SearchPaletteController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import ShoppingCatalogController from "./shopping_catalog_controller"
application.register("shopping-catalog", ShoppingCatalogController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import SonnerController from "./sonner_controller"
application.register("sonner", SonnerController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import ToggleGroupController from "./toggle_group_controller"
application.register("toggle-group", ToggleGroupController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import VoiceDictationController from "./voice_dictation_controller"
application.register("voice-dictation", VoiceDictationController)

import WakeLockController from "./wake_lock_controller"
application.register("wake-lock", WakeLockController)
