// design-sync: emits ds-bundle/tokens/theme.css (+ tokens.md) from the app's
// hand-edited token source. Mechanical transform — never edit the output.
//
// ASSUMPTION: app/assets/stylesheets/application.tailwind.css keeps its three
// top-level blocks (`@theme {`, `:root {`, `.dark {`) closed by a `}` at column 0.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(join(repo, "app/assets/stylesheets/application.tailwind.css"), "utf8");

const block = (opener) => {
  const start = src.indexOf(opener);
  if (start === -1) throw new Error(`block not found: ${opener}`);
  const end = src.indexOf("\n}", start);
  return src.slice(start + opener.length, end).trimEnd();
};

const theme = block("@theme {");
const root = block(":root {");
const dark = block(".dark {");

const css = `/* Hestia design tokens — generated by .design-sync/build-tokens.mjs from
   app/assets/stylesheets/application.tailwind.css. Do not edit. */

/* Raw palette, fonts, radii (full set — the compiled bundle prunes unused ones) */
:root, :host {
${theme}
}

/* Semantic tokens — light */
:root {
${root}
}

/* Semantic tokens — dark (toggle by adding class="dark" on <html>) */
.dark {
${dark}
}
`;

const outDir = join(repo, "ds-bundle/tokens");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "theme.css"), css);

// tokens.md — readable index of every custom property with its raw value.
const rows = (text) =>
  [...text.matchAll(/^\s*(--[\w-]+):\s*([^;]+);/gm)].map(([, name, value]) => [name, value.trim()]);

const table = (pairs) =>
  ["| Token | Value |", "| --- | --- |", ...pairs.map(([n, v]) => `| \`${n}\` | \`${v.replace(/\|/g, "\\|")}\` |`)].join("\n");

const md = `# Hestia design tokens

Generated from \`app/assets/stylesheets/application.tailwind.css\`. All tokens are CSS
custom properties available in \`styles.css\`. Semantic tokens swap values when
\`class="dark"\` is set on \`<html>\` — always prefer them over raw palette values.

## Raw palette, fonts, radii (\`@theme\`)

${table(rows(theme))}

## Semantic tokens — light (\`:root\`)

${table(rows(root))}

## Semantic tokens — dark (\`.dark\`)

${table(rows(dark))}
`;
writeFileSync(join(outDir, "tokens.md"), md);
console.log("wrote ds-bundle/tokens/theme.css and tokens.md");
