default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: hestia
  password: changeme_dev_only

development:
  <<: *default
  database: hestia_development

test:
  <<: *default
  database: hestia_test

production:
  primary: &primary_production
    <<: *default
    database: hestia_production
    username: hestia
    password: <%= ENV["MON_PROJET_FOYER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: hestia_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hestia_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hestia_production_cable
    migrations_paths: db/cable_migrate
